version: '3.9'

services:
  ui:
    build: ./ui
    image: brainstorm-ui
    container_name: ui
    ports:
      - "80:80"
    depends_on:
      - entity-service

  entity-service:
    build: ./entity-service
    image: brainstorm-entity-service
    container_name: entity-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/brainstorm
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=brainstorm
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
