server:
  port: 8510

spring:
  data:
    postgresql:
      host: localhost
      port: 5432
      database: brainstorm
      username: ${db.username}
      password: ${db.password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"

encrypt:
  key-store:
    location: classpath:keystore.jks
    password: jimiJava1!
    alias: alias
    secret: jimiJava1!

db:
  username: ENC({cipher}encrypted-username)
  password: ENC({cipher}encrypted-password)


