spring:
  config:
    name: application
    activate:
      on-profile:
        - default
---
server:
  port: 8510
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/brainstorm
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: com.brainstorm.config.BrainStormNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

