spring:
  config:
    name: application
    activate: always
  profiles:
    active: default,secrets
---
spring:
  profiles: default
  datasource:
    url: jdbc:postgresql://localhost:5432/brainstorm
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        dialect: org.hibernate.dialect.PostgreSQLDialect
